#include "aui/translation.h"

#include <QCoreApplication>

std::u16string Translate(std::string_view text) {
  // The .ts files generated by lupdate from client_utils.cpp / view code all
  // use the empty translation context (see `<name></name>` in client_ru.ts),
  // so we must look up with an empty context too. Using QObject::tr() here
  // would look up under context "QObject" and silently miss every entry.
  return QCoreApplication::translate("", std::string(text).c_str())
      .toStdU16String();
}
