#include "aui/translation.h"

#include <QCoreApplication>
#include <QtGlobal>

namespace {

// Keep service display names in the empty translation context used by
// Translate(). These labels are registered outside QObject-based UI code.
[[maybe_unused]] constexpr const char* kTranslationNoops[] = {
    QT_TRANSLATE_NOOP("", "Telecontrol"),
    QT_TRANSLATE_NOOP("", "Vidicon"),
    QT_TRANSLATE_NOOP("", "Loading"),
};

}  // namespace

std::u16string Translate(std::string_view text) {
  // The .ts files generated by lupdate from client_utils.cpp / view code all
  // use the empty translation context (see `<name></name>` in client_ru.ts),
  // so we must look up with an empty context too. Using QObject::tr() here
  // would look up under context "QObject" and silently miss every entry.
  return QCoreApplication::translate("", std::string(text).c_str())
      .toStdU16String();
}
