#include "aui/translation.h"

#include <QCoreApplication>
#include <QLocale>
#include <QSettings>
#include <QString>
#include <QtGlobal>

#include <utility>

namespace {

// Keep service display names in the empty translation context used by
// Translate(). These labels are registered outside QObject-based UI code.
[[maybe_unused]] constexpr const char* kTranslationNoops[] = {
    QT_TRANSLATE_NOOP("", "Telecontrol"),
    QT_TRANSLATE_NOOP("", "Vidicon"),
    QT_TRANSLATE_NOOP("", "Loading"),
};

}  // namespace

// The startup `--locale` override, injected by the app layer. A function-local
// rather than a namespace-scope object so it is not a static global; it is
// written once at startup, before any window or session exists, and only read
// afterwards.
std::string& UiLocaleOverride() {
  static std::string override_locale;
  return override_locale;
}

std::string UiLocaleName() {
  // The operator's stored choice wins, then the startup override, then the
  // system language. `InstalledTranslation` resolves the catalogs it installs
  // through this same function, so the window's language and the language the
  // session asks the server for are the same by construction rather than by
  // two lists happening to agree.
  if (const QString stored = QSettings{}.value("LocaleName").toString();
      !stored.isEmpty()) {
    return stored.toStdString();
  }
  if (!UiLocaleOverride().empty())
    return UiLocaleOverride();
  return QLocale::system().bcp47Name().toStdString();
}

void SetUiLocaleOverride(std::string locale_name) {
  UiLocaleOverride() = std::move(locale_name);
}

std::u16string Translate(std::string_view text) {
  // The .ts files generated by lupdate from client_utils.cpp / view code all
  // use the empty translation context (see `<name></name>` in client_ru.ts),
  // so we must look up with an empty context too. Using QObject::tr() here
  // would look up under context "QObject" and silently miss every entry.
  return QCoreApplication::translate("", std::string(text).c_str())
      .toStdU16String();
}
