//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by common.rc
//
#define IDC_DELALL                      4
#define IDD_ABOUTBOX                    100
#define IDD_LIMITS                      101
#define ID_VIEW_ADD_TO_FAVOURITES       101
#define IDD_IEC60870_DEVICE             102
#define IDD_TS_FORMAT                   103
#define IDD_MESSAGES                    104
#define ID_GRAPH_VIEW                   104
#define ID_TS_FORMATS_VIEW              105
#define IDB_EVENT_SEVERITIES            105
#define ID_CELLS_VIEW                   106
#define IDD_NEW_SERVICE_ITEMS           106
#define IDR_TABLE_BTN                   106
#define ID_SIMULATION_ITEMS_VIEW        107
#define ID_HARDWARE_VIEW                108
#define ID_WIN_RENAME                   108
#define ID_USERS_VIEW                   109
#define IDS_MAIN_WINDOW_TITLE           109
#define ID_ACKNOWLEDGE_CURRENT          110
#define IDR_REGISTRY1                   110
#define IDR_OPC_SERVER                  110
#define ID_ACKNOWLEDGE_ALL              111
#define IDR_REGISTRY2                   111
#define IDR_OPC_HDA_SERVER              111
#define ID_SHEET_VIEW                   112
#define IDR_OLEDB                       112
#define IDR_OLEDB_PROVIDER              112
#define ID_SUMMARY_VIEW                 113
#define ID_TIMED_DATA_VIEW              114
#define ID_WRITE                        115
#define IDB_COPY                        115
#define ID_WRITE_MANUAL                 116
#define IDB_PNG2                        116
#define IDB_PASTE                       116
#define ID_UNLOCK_ITEM                  117
#define IDB_APP                         117
#define ID_APPLICATION                  117
#define ID_EDIT_LIMITS                  118
#define ID_ITEM_PARAMS                  119
#define ID_TABLE_CONFIG                 120
#define ID_OBJECT_VIEW                  121
#define ID_EVENT_VIEW                   122
#define ID_EVENT_JOURNAL_VIEW           123
#define ID_FAVOURITES_VIEW              124
#define ID_PORTFOLIO_VIEW               125
#define ID_WATCH_VIEW                   126
#define ID_STATISTICS_VIEW              127
#define ID_MOVE_UP                      127
#define ID_WEB_VIEW                     128
#define ID_MOVE_DOWN                    128
#define IDR_MAINFRAME                   128
#define ID_DELETE                       129
#define IDR_MDICHILD                    129
#define IDR_CUSTABLE                    129
#define ID_OPEN_GRAPH                   130
#define IDS_VERSION_STRING              130
#define ID_OPEN_TABLE                   131
#define IDS_LOCAL_SERVER                131
#define ID_SETUP                        132
#define ID_PRINT                        133
#define ID_EXPORT_CSV                   134
#define ID_NEW_IEC60870_LINK101         135
#define ID_NEW_IEC60870_LINK104         136
#define ID_OPEN_SUMMARY                 137
#define ID_OPEN_DISPLAY                 138
#define ID_OPEN_EVENTS                  139
#define ID_DEV1_REFR                    140
#define ID_DEV1_SYNC                    141
#define ID_OPEN_WATCH                   142
#define ID_CHANGE_PASSWORD              145
#define ID_ITEM_ENABLE                  146
#define ID_ITEM_DISABLE                 147
#define ID_TRANSMISSION_VIEW            149
#define ID_MODUS_VIEW                   150
#define ID_HISTORICAL_EVENTS            151
#define ID_PROPERTY_VIEW                152
#define ID_TABLE_EDITOR                 153
#define ID_MODUS_TOOLBAR                154
#define ID_MODUS_STATUSBAR              155
#define ID_CURRENT_EVENTS               156
#define ID_TIME_RANGE_DAY               157
#define ID_TIME_RANGE_WEEK              158
#define ID_TIME_RANGE_MONTH             159
#define ID_EDIT                         161
#define ID_PRINT_PREVIEW                162
#define ID_VIEW_CHANGE_TITLE            164
#define ID_VIEW_CLOSE                   165
#define ID_TIME_RANGE_CUSTOM            166
#define ID_SEVERITY_HIGH                167
#define ID_SEVERITY_ALL                 168
#define ID_SEVERITY_CUSTOM              169
#define ID_NEW_PORTFOLIO                171
#define ID_PAUSE                        172
#define ID_NEW_SERVICE_ITEMS            174
#define ID_ADD_MULTIPLE_ITEMS           175
#define ID_VIEW_CURSOR                  176
#define ID_SAVE_AS                      177
#define ID_OPEN_DEVICE_METRICS          178
#define ID_EXCEL_REPORT_VIEW            179
#define ID_OPEN_GROUP_TABLE             180
#define ID_VIDICON_DISPLAY_VIEW         182
#define ID_ABOUT_QT                     184
#define ID_WINDOW_SPLIT_HORZ            185
#define ID_WINDOW_SPLIT_VERT            186
#define ID_AGGREGATION_END              187
#define ID_AGGREGATION_COUNT            188
#define ID_AGGREGATION_MIN              189
#define ID_AGGREGATION_MAX              190
#define ID_AGGREGATION_AVG              191
#define ID_AGGREGATION_SUM              192
#define ID_INTERVAL_1M                  193
#define ID_INTERVAL_5M                  194
#define ID_INTERVAL_15M                 195
#define ID_INTERVAL_30M                 196
#define ID_INTERVAL_1H                  197
#define ID_INTERVAL_12H                 198
#define ID_INTERVAL_1D                  199
#define ID_AGGREGATION_START            200
#define IDR_STRUCT_POPUP                201
#define ID_GRAPH_COLOR                  201
#define IDD_LOGIN                       202
#define IDR_EVENT_POPUP                 202
#define ID_EXPORT_EXCEL                 202
#define IDR_PAGE_BTN                    203
#define IDB_ITEMS                       206
#define IDD_SUMM                        207
#define IDR_GRAPH_POPUP                 209
#define IDR_TABLE_POPUP                 210
#define IDD_WRITE_TIT                   211
#define IDD_WRITE_TS                    212
#define IDR_ITEM_POPUP                  215
#define IDD_TS                          217
#define IDD_TIT                         218
#define IDR_CUSTABLE_POPUP              218
#define IDR_SHEET_POPUP                 218
#define IDD_LIMIT                       219
#define IDR_MAIN_USER                   219
#define IDD_IEC60870_LINK101            221
#define IDD_MSG                         222
#define IDD_PROMPT                      225
#define IDR_LOG_POPUP                   226
#define IDD_PROGRESS                    227
#define IDD_CHANGE_PASSWORD             229
#define IDR_TIMEVAL_POPUP               229
#define IDR_MODUS_POPUP                 230
#define IDR_FAVOR_POPUP                 231
#define IDR_PFOLIO_POPUP                232
#define IDR_GRID_POPUP                  233
#define IDB_WIN_TYPES                   236
#define IDD_ADD_FAVOURITES              237
#define IDB_ACTIONS                     240
#define IDD_SELITEM                     243
#define IDD_FILTER                      244
#define IDD_TS_PARAMS                   245
#define IDD_GRAPH_SETUP                 246
#define IDD_IEC60870_LINK104            247
#define IDD_GROUP                       250
#define IDD_SIMULATION_ITEM             251
#define IDC_TITLE                       252
#define IDD_BASE_EDITOR                 252
#define ID_TOOLBAR_HIDDEN               253
#define IDD_INTERVAL                    253
#define IDD_TIME_RANGE                  253
#define IDD_NEW_SERVICE_ITEMS1          254
#define IDD_NEW_ITEMS                   254
#define IDD_LINK_MODBUS                 255
#define IDD_CONNECTION_NETWORK          256
#define IDD_CONNECTION_SERIAL           257
#define IDB_PRINTER                     257
#define IDD_MODBUS_DEVICE               258
#define IDB_DELETE                      258
#define IDD_TRANSPORT                   259
#define IDD_HISTORICAL_DB               260
#define IDB_OPEN_EVENTS                 261
#define IDD_IEC61850_DEVICE             261
#define IDD_IEC61850_REF                262
#define IDD_IEC61850_RCB                262
#define IDB_TIMED_DATA                  263
#define IDB_UNLOCK                      264
#define IDB_WRITE                       265
#define IDB_WRITE_MANUAL                266
#define IDB_SUMMARY                     267
#define IDB_RECORD_EDITOR               269
#define ID_TABLE_VIEW                   270
#define IDB_ACKNOWLEDGE_ALL             271
#define IDC_DESC                        320
#define IDC_VALUE                       321
#define IDC_UNITS                       322
#define IDC_LOCK                        323
#define IDC_CURRENT                     324
#define IDC_CURRENT2                    325
#define IDC_CONDITION                   325
#define IDC_STATE                       326
#define ID_NEW_PROPERTY_VIEW            327
#define IDC_NAME                        1000
#define IDC_PASSWORD                    1001
#define IDC_ALIAS                       1001
#define IDC_END_DATE                    1001
#define IDC_START_DATE                  1002
#define IDC_DATETIMEPICKER1             1003
#define IDC_START_TIME_CHECK            1003
#define IDC_DATETIMEPICKER2             1004
#define IDC_END_TIME_CHECK              1004
#define IDC_START_TIME                  1005
#define IDC_END_TIME                    1006
#define IDC_STALE_PERIOD                1007
#define IDC_HOST                        1008
#define IDC_STALE_PERIOD2               1008
#define IDC_STATUS                      1009
#define IDC_HISTORY_DEPTH               1009
#define IDC_DEVICES_COMBO               1010
#define IDC_CHANNELS_LIST               1011
#define ID_OK                           1012
#define IDC_ADDRESS_PREFIX              1012
#define IDC_PATH_PREFIX                 1012
#define ID_CANCEL                       1013
#define IDC_STARTING_ADDRESS            1013
#define IDC_STARTING_NUMBER             1014
#define IDC_DEV                         1015
#define IDC_SPIN2                       1015
#define IDC_STARTING_NUMBER_SPIN        1015
#define IDC_ITEM                        1016
#define IDC_COUNT                       1016
#define IDC_CHAN                        1017
#define IDC_SPIN3                       1017
#define IDC_COUNT_SPIN                  1017
#define IDC_NAME_PREFIX                 1018
#define IDC_TYPE                        1019
#define IDC_LBL_OPEN                    1020
#define IDC_TYPE_TIT                    1020
#define IDC_LBL_CLOSE                   1021
#define IDC_SPIN4                       1021
#define IDC_STARTING_ADDRESS_SPIN       1021
#define IDC_CLR_OPEN                    1022
#define IDC_CONNECTION_TYPE_COMBO       1022
#define IDC_SYNC                        1023
#define IDC_INV                         1023
#define IDC_CLAMP                       1023
#define IDC_CUSTOM1                     1023
#define IDC_CONNECTION_FRAME            1023
#define IDC_CLR_CLOSE                   1024
#define IDC_BUTTON1                     1024
#define IDC_CTRL                        1025
#define IDC_COMBO1                      1025
#define IDC_PORT_COMBO                  1025
#define IDC_FOLDER                      1025
#define IDC_HISTORICAL_DB_COMBO         1025
#define IDC_SERVER_TYPE                 1025
#define IDC_SEV                         1026
#define IDC_HOST_EDIT                   1026
#define IDC_EU_LO                       1027
#define IDC_PORT_EDIT                   1027
#define IDC_EU_HI                       1028
#define IDC_BAUDRATE_COMBO              1028
#define IDC_IR_LO                       1029
#define IDC_ADDRESS_EDIT                1029
#define IDC_IR_HI                       1030
#define IDC_ADDRESS_SPIN                1030
#define IDC_CONV_NONE                   1031
#define IDC_REPEAT_COUNT_EDIT           1031
#define IDC_CONV_LINE                   1032
#define IDC_REPEAT_COUNT_SPIN           1032
#define IDC_FMT                         1033
#define IDC_TYPE_COMBO                  1033
#define IDC_REPEAT_COUNT_EDIT2          1033
#define IDC_RESPONSE_TIMEOUT            1033
#define IDC_SEV_SPIN                    1034
#define IDC_EDIT_TRANSPORT              1034
#define IDC_REPEAT_COUNT_SPIN2          1034
#define IDC_LIMIT_LOLO                  1035
#define IDC_TRANSPORT_EDIT              1035
#define IDC_LIMIT_HIHI                  1036
#define IDC_LIMIT_HI                    1037
#define IDC_BITCOUNT_COMBO              1037
#define IDC_EDIT                        1038
#define IDC_LIMIT_LO                    1038
#define IDC_MAX_SEND                    1038
#define IDC_ARC                         1038
#define IDC_PARITY_COMBO                1038
#define IDC_DEPTH_EDIT                  1038
#define IDC_MAX_RECV                    1039
#define IDC_STOPBITS_COMBO              1039
#define IDC_DEPTH_SPIN                  1039
#define IDC_INTER_PER                   1040
#define IDC_COMBO6                      1040
#define IDC_FLOWCONTROL_COMBO           1040
#define IDC_SYNC_PER                    1041
#define IDC_LIST                        1041
#define IDC_MFCSHELLTREE1               1041
#define IDC_CON_TIMEO                   1042
#define IDC_MODBUS_RTU                  1042
#define IDC_TERM_TIMEO                  1043
#define IDC_COMBOPERIOD                 1043
#define IDC_MODBUS_ASCII                1043
#define IDC_PROMPT                      1044
#define IDC_MODBUS_TCP2                 1044
#define IDC_MODBUS_TCP                  1044
#define IDC_POLL                        1044
#define IDC_INTER                       1044
#define IDC_DATETIMEPICKER3             1045
#define IDC_EDIT1                       1045
#define IDC_APERTURE                    1045
#define IDC_DATETIMEPICKER4             1046
#define IDC_REF                         1046
#define IDC_PROGRESS                    1047
#define IDC_UTC_TIME                    1047
#define IDC_EXACT_TIME                  1048
#define IDC_TIME_CHECK                  1048
#define IDC_PORT                        1049
#define IDC_TIME_GROUP                  1049
#define IDC_FORMULA_CHECK               1050
#define IDC_EDIT2                       1051
#define IDC_DEADBAND                    1051
#define IDC_CUR_PASSW                   1058
#define IDC_FORMULA                     1059
#define IDC_PASSW2                      1060
#define IDC_TREE                        1062
#define IDC_ITEMS                       1067
#define IDC_FILTER                      1069
#define IDC_FILTER_ADD                  1070
#define IDC_FILTER_DEL                  1071
#define IDC_ITEM_ADD                    1072
#define IDC_PARAMS                      1073
#define IDC_ITEM_DEL                    1073
#define IDC_SIMULATION_SIGNAL           1074
#define IDC_COLOR                       1075
#define IDC_LINE_WEIGHT                 1077
#define IDC_LINE_WEIGHT_UPDOWN          1078
#define IDC_SETUP                       1085
#define IDC_IEC104                      1086
#define IDC_IEC101                      1087
#define IDC_LEN_DEV                     1088
#define IDC_LEN_COT                     1089
#define IDC_ADDR                        1089
#define IDC_LEN_ADDR                    1090
#define IDC_LINK_ADDR                   1090
#define IDC_LINK_ADDR_LABEL             1091
#define IDC_SIMULATE                    1092
#define IDC_RANDOM                      1093
#define IDC_STALE_CHECK                 1093
#define IDC_RAMP                        1094
#define IDC_STEP                        1095
#define IDC_SIN                         1096
#define IDC_COS                         1097
#define IDC_PERIOD                      1098
#define IDC_UPDATE_RATE                 1099
#define IDC_AUTO_LOGIN                  1100
#define IDC_PHASE                       1100
#define IDC_DISABLED                    1101
#define IDC_SLAVE                       1102
#define IDC_COLLECT_DATA                1103
#define IDC_CRC_PROTECTION              1104
#define IDC_NUM_SEND_REPEATS            1105
#define IDC_SEND_TIMEOUT                1106
#define IDC_RECEIVE_TIMEOUT             1107
#define IDC_IDLE_TIMEOUT                1108
#define IDC_ANONYMOUS                   1109
#define IDC_IEC60870_LINK_T0            1110
#define IDC_VERSION                     1111
#define IDC_POLL1                       2001
#define IDC_POLL2                       2002
#define IDC_POLL3                       2003
#define IDC_POLL4                       2004
#define IDC_POLL5                       2005
#define IDC_POLL6                       2006
#define IDC_POLL7                       2007
#define IDC_POLL8                       2008
#define IDC_POLL9                       2009
#define IDC_POLL10                      2010
#define IDC_POLL11                      2011
#define IDC_POLL12                      2012
#define IDC_POLL13                      2013
#define IDC_POLL14                      2014
#define IDC_POLL15                      2015
#define IDC_POLL16                      2016
#define ID_HISTORICAL_DB_VIEW           2017
#define ID_GRAPH_ZOOM                   4001
#define ID_MODUS2_MODE                  4021
#define ID_EXPORT_CONFIGURATION_TO_EXCEL 4022
#define ID_IMPORT_CONFIGURATION_FROM_EXCEL 4023
#define ID_LOGIN                        4024
#define ID_LOGOFF                       4025
#define ID_VIEW_PUBLIC_FOLDER           4026
#define ID_NODES_VIEW                   4029
#define ID_SORT_NONE                    4030
#define ID_SORT_ALIAS                   4032
#define ID_POPUP_4033                   4033
#define ID_PAGE_DELETE                  32787
#define ID_VIEW_LEGEND                  32797
#define ID_NOW                          32830
#define ID_RENAME                       32838
#define ID_HIST                         32840
#define IDC_DEL                         32848
#define ID_GRAPH_ADD_PANE               32856
#define ID_GRAPH_DELETE_PANE            32858
#define ID_COLORS                       32864
#define ID_CURBOX                       32874
#define ID_PAGE_RENAME                  32875
#define ID_SAVE                         32885
#define ID_COPY                         32887
#define ID_PASTE                        32889
#define ID_CUT                          32891
#define ID_SHOW_WRITEOK                 32893
#define ID_SHOW_EVENTS                  32895
#define ID_HIDE_EVENTS                  32897
#define ID_ITEM_COMMANDS                32903
#define ID_WRITE_CONFIRMATION           32921
#define ID_OPEN                         32945
#define ID_BUTTON32946                  32946
#define ID_ADD_ITEMS                    32960
#define ID_EVENT_FLASH_WINDOW           32979
#define ID_EVENT_PLAY_SOUND             32980
#define ID_GRAPH_DOTS                   32984
#define ID_GRAPH_STEPS                  32985
#define ID_TOOLBAR_TOP                  32989
#define ID_TOOLBAR_LEFT                 32990
#define ID_SORT_NAME                    32991
#define ID_SORT_CHANNEL                 32992
#define ID_CLEAR_ALL                    32993
#define ID_BUTTON33002                  33002
#define ID_BUTTON33003                  33003
#define ID_HELP_MANUAL                  33009
#define ID__                            33011
#define ID__33013                       33013
#define ID_PAGE_NEW                     34122
#define ID_OPT_SPEECH                   34123
#define ID_NEW                          40000
#define ID_NEW_DISPLAY_0                40100
#define ID_NEW_REPORT_0                 40200
#define ID_PAGE_0                       40300
#define ID_COLOR_0                      40400
#define ID_WIN_0                        40500
#define ID_TRASH_0                      40600
#define ID_FAV_TABLE_0                  40800
#define ID_FAV_GRAPH_0                  40900
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         4034
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           203
#endif
#endif
