INSTALL(DIRECTORY schemes
  DESTINATION .
  COMPONENT Client)

INSTALL(FILES "tools/sqlite/sqlite3.exe"
  DESTINATION bin
  COMPONENT Server)

INSTALL(FILES "docs/scada/scada.pdf"
  DESTINATION docs
  COMPONENT Documentation)

SET(CPACK_PACKAGE_VERSION_MAJOR ${project_version_major})
SET(CPACK_PACKAGE_VERSION_MINOR ${project_version_minor})
SET(CPACK_PACKAGE_VERSION_PATCH ${project_version_patch})

SET(CPACK_GENERATOR WIX)
SET(CPACK_WIX_CULTURES "ru-RU")
SET(CPACK_PACKAGE_NAME "ОИК Телеконтроль")
SET(CPACK_PACKAGE_VENDOR "ООО Телеконтроль")
SET(CPACK_PACKAGE_FILE_NAME "telecontrol-scada-${project_version_major}.${project_version_minor}.${project_version_patch}")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "ОИК Телеконтроль")
SET(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/license.txt")
SET(CPACK_WIX_UPGRADE_GUID "A28F5481-81B8-4A73-8E93-6ACF023FB9BF")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Telecontrol SCADA")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "SCADA")

# SET(CPACK_COMPONENTS_ALL server client documentation)
SET(CPACK_COMPONENT_SERVER_DISPLAY_NAME "Сервер")
SET(CPACK_COMPONENT_CLIENT_DISPLAY_NAME "Клиент")
SET(CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME "Документация")

LIST(APPEND CPACK_PACKAGE_EXECUTABLES "client" "Клиент")
LIST(APPEND CPACK_PACKAGE_EXECUTABLES "server" "Сервер (консоль)")

LIST(APPEND CPACK_CREATE_DESKTOP_LINKS "client")
LIST(APPEND CPACK_CREATE_DESKTOP_LINKS "server")

# SET(CPACK_WIX_PATCH_FILE "${CMAKE_CURRENT_SOURCE_DIR}/install-wix-patch.xml")

# LIST(APPEND CPACK_WIX_EXTRA_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/install-extras.wxs")

SET(CPACK_WIX_TEMPLATE "${CMAKE_CURRENT_SOURCE_DIR}/install-wix-template.wxs")

INCLUDE(CPack)
